# Generated by Django 3.0 on 2022-07-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone_no', models.IntegerField(default=0)),
                ('user_dob', models.DateField(default=0)),
                ('user_password1', models.CharField(max_length=25)),
                ('user_password2', models.CharField(max_length=25)),
            ],
        ),
    ]
